/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_sl_web_server_Aes */

#ifndef _Included_com_sl_web_server_Aes
#define _Included_com_sl_web_server_Aes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sl_web_server_Aes
 * Method:    encrypt
 * Signature: ([C[C)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_sl_web_server_code_Aes_encrypt
  (JNIEnv *, jobject, jcharArray, jcharArray);

/*
 * Class:     com_sl_web_server_Aes
 * Method:    decrypt
 * Signature: ([C[C)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_sl_web_server_code_Aes_decrypt
  (JNIEnv *, jobject, jcharArray, jcharArray);

/*
 * Class:     com_sl_web_server_Aes
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sl_web_server_code_Aes_version
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
